// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/7/2024, 4:35:42 PM
const configMerger = require("/Users/eladventures/Desktop/codes/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/eladventures/Desktop/codes/fortcupine/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/eladventures/Desktop/codes/fortcupine/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/eladventures/Desktop/codes/fortcupine/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/eladventures/Desktop/codes/fortcupine/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/eladventures/Desktop/codes/fortcupine/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/eladventures/Desktop/codes/fortcupine/src/plugins/**/*.{js,ts,mjs}","/Users/eladventures/Desktop/codes/fortcupine/src/composables/**/*.{js,ts,mjs}","/Users/eladventures/Desktop/codes/fortcupine/src/utils/**/*.{js,ts,mjs}","/Users/eladventures/Desktop/codes/fortcupine/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/eladventures/Desktop/codes/fortcupine/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/eladventures/Desktop/codes/fortcupine/src/app.config.{js,ts,mjs}"] }));

module.exports = config
